#!/bin/sh
# ZX-UX Unix ZX Spectrum 48K SDK © 2026 SANYALnet Labs supratim-sanyal.blogspot.com
#
# SANYALnet Labs Non-Commercial License, attribution to SANYALnet Labs required, see LICENSE for more information
exec python3 -B "$(dirname "$0")/compiler/c48b2tap.py" "$@"
