#!/bin/sh
# ============================================================================
# Copyright (c) 2026 SANYALnet Labs.
# Proprietary rights reserved except as expressly licensed herein.
#
# ZX-UX C48 SDK
# This file is governed by the SANYALnet Labs Non-Commercial License in the
# root LICENSE file. Non-Commercial use is permitted; Commercial Use and use
# restricted model training is prohibited unless separately authorized.
#
# Attribution required: SANYALnet Labs. See LICENSE for full terms,
# warranty disclaimer, termination, patent, trademark, and governing-law
# provisions.
# ============================================================================
exec python3 -B "$(dirname "$0")/compiler/c48srctap.py" "$@"
